version: "3"
services:
  hadibar:
    image: killingspark/hadibar:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"
    networks:
      - webnet
    volumes:
      - $HOME/.cache/hadibar:/app/data
networks:
  webnet:
